Q1. What is the difference between the `is` operator and the `==` operator? Give one example wheretwo variables return True for `==` but False for `is`.

==operator checks whether two variable have same value.
is operator checks whether two variables refer to the same object in memory.
example:
a = [1, 2, 3]
b = [1, 2, 3]

print(a == b)  # True
print(a is b)  # False
Explanation:
a and b contain the same values, so a == b is True.
But they are two different list objects in memory, so a is b is False.

Q2. Classify the following as Mutable or Immutable: list, tuple, set, dict, str, int, float, bool,frozenset. Explain in one line WHY immutability matters in real code.

Data Type	Classification	Why?
1.list       Mutable        Elements can be changed after creation.
2.tuple      Immutable      Elements cannot be changed after creation.
3.set        Mutable        Elements can be added or removed.
4.dict      Mutable         Key-value pairs can be added, removed, or changed.
5.str	     Immutable	Characters cannot be changed after creation.
6.int	    Immutable	 Its value cannot be changed after creation.
7.float	  Immutable	  Its value cannot be changed after creation.
8.bool	  Immutable	True and False values cannot be modified.
9.frozenset	 Immutable	Elements cannot be added or removed.



Q3.Predict the output of `print(0.1 + 0.2 == 0.3)`. Then explain WHY this happens. (Hint: it is not aPython bug.)

->The output will be the "False"
Why does this happen?

This happens because floating-point numbers are stored in binary, and numbers like 0.1 and 0.2 cannot be represented exactly in binary.




Q4. Both list and tuple can store ordered collections. Give 3 concrete situations where you wouldCHOOSE a tuple over a list, and explain the reasoning behind each.

1.Storing fixed data
Example: coordinates = (12.97, 77.59)
Reason: Coordinates should not be changed accidentally, so a tuple is suitable.
2.Returning multiple values from a function
Example: return (name, age, salary)
Reason: A tuple can group related values together and clearly represent a fixed result.
3.Using data as a dictionary key
Example: location = (12, 77) can be used as a dictionary key.
Reason: Tuples are immutable and therefore can be used as dictionary keys, whereas lists cannot.

In short: Choose a tuple when the collection should remain fixed and unchanged.

Q5. Why is dictionary lookup O(1) on average while searching for a value in a list using `in` is O(n)?Explain in plain English without using the word "hash" - then explain it again WITH the word "hash".


1.Without using the word “hash”

Dictionary lookup is O(1) on average because Python can go almost directly to the location where a key's data is stored. It does not need to check every item.

List search using in is O(n) because Python may have to check each element one by one until it finds the value.
example:
my_list = [10, 20, 30, 40, 50]
30 in my_list
2.With the word “hash”

A dictionary uses a hash table. Python applies a hash function to the key to calculate where the key-value pair should be stored. This allows Python to find the required item directly on average, giving O(1) lookup time.

A list does not use this mechanism. It searches elements one by one, so searching can take O(n) time.

Simple memory trick:

Dictionary → direct access → O(1) average
List → one-by-one search → O(n)

Q6. What is the difference between `range()` and `numpy.arange()`? Mention at least 3 differences,one of them should involve floats.


Feature 	  range()	 numpy.arange()
1. Library	Built-in Python function	NumPy function
2. Data type	Produces a range object, mainly for integers	 Produces a NumPy array
3. Floats	Does not support float steps directly	Supports float steps
4. Usage	Commonly used in loops	Useful for numerical calculations and arrays



Q7. What is the difference between `list.append(x)`, `list.extend(x)`, and `list.insert(i, x)`? For each,show what happens when `x = [4, 5]` is added to `a = [1, 2, 3]`.

a = [1, 2, 3]
x = [4, 5]

Method	What it does	Result
append(x)	Adds x as one single element at the end	[1, 2, 3, [4, 5]]
extend(x)	Adds each element of x separately	[1, 2, 3, 4, 5]
insert(i, x)	Adds x at a specific position	[1, 2, [4, 5], 3] if i = 2

examples:
a = [1, 2, 3]
x = [4, 5]

a.append(x)
print(a)
# [1, 2, 3, [4, 5]]

a = [1, 2, 3]
a.extend(x)
print(a)
# [1, 2, 3, 4, 5]

a = [1, 2, 3]
a.insert(2, x)
print(a)
# [1, 2, [4, 5], 3]



What does this line do, and what are the values of a, b, c after execution?a, *b, c = [10, 20, 30, 40, 50]

a, *b, c = [10, 20, 30, 40, 50]
This is called extended unpacking. The *b collects all the remaining middle values into a list.

So:

a = 10
b = [20, 30, 40]
c = 50

a, *b, c = [10, 20]

This works:

a = 10
b = []
c = 20

The starred variable b can be an empty list.

a, *b, c = [10]

This gives a ValueError.

Reason: We need at least two values—one for a and one for c. But the list contains only one value.

ValueError: not enough values to unpack
Easy rule:

a, *b, c needs at least 2 values.


Q9. Explain the difference between `/`, `//`, `%`, and `**` operators in Python. For each, give theoutput of the operation when applied to (-7, 2)

 Operator  Meaning      Operation   Output
1./        Division     -7 / 2      -3.5
2.//      Floordivision -7 // 2      -4
3.%     Modulus(remainder) -7 % 2     1
4.**     Power             -7 ** 2   -49

Why is NumPy significantly faster than Python lists for numerical operations? Give 3 reasons, atleast one should mention memory layout.  


NumPy is significantly faster than Python lists for numerical operations because:

Better memory layout: NumPy arrays store elements of the same data type in continuous (contiguous) memory, so the computer can access them efficiently.
Vectorized operations: NumPy can perform operations on many elements at once instead of using Python for loops for each element.
Optimized low-level code: Many NumPy operations are implemented in C/C/Fortran, which runs much faster than normal Python loops.

In short: NumPy is faster because it uses efficient memory storage, vectorization, and optimized low-level code.

In [1]:
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3

matrix1[0][0] = 99
matrix2[0][0] = 99

print(matrix1)
print(matrix2)

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


In [2]:
x = [1, 2, 3]
y = x

x = x + [4]

print("x =", x)
print("y =", y)

a = [1, 2, 3]
b = a

a += [4]

print("a =", a)
print("b =", b)

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


In [3]:
for i in range(5):
    pass

print(i)

for j in range(0):
    pass

print(j)

4


NameError: name 'j' is not defined

In [5]:
print("10" + "20")
print(10 + 20)
print("10" * 3)
print(10 * "3")

print("10" + 20)
print(int("10") + 20)

1020
30
101010
3333333333


TypeError: can only concatenate str (not "int") to str

Q16. Swap two numbers WITHOUT using a third variable
(a) Using Arithmetic

a = 10
b = 20

a = a + b
b = a - b
a = a - b

print(a, b)


Using XOR (^)
a = 10
b = 20

a = a ^ b
b = a ^ b
a = a ^ b

print(a, b)
Using Tuple Unpacking

a = 10
b = 20

a, b = b, a

print(a, b)


In [7]:
price = float(input("Enter item price: ₹"))
quantity = int(input("Enter quantity: "))

subtotal = price * quantity
gst = subtotal * 0.18

if subtotal < 500:
    delivery = 40
else:
    delivery = 0

total = subtotal + gst + delivery

print(f"Subtotal: ₹{subtotal:.2f}")
print(f"GST (18%): ₹{gst:.2f}")
print(f"Delivery: ₹{delivery:.2f}")
print("------------------------")
print(f"Total: ₹{total:.2f}")

Enter item price: ₹150
Enter quantity: 3
Subtotal: ₹450.00
GST (18%): ₹81.00
Delivery: ₹40.00
------------------------
Total: ₹571.00


In [8]:
value = float(input("Enter temperature value: "))
unit = input("Enter unit (C or F): ").upper()

if unit == "C":
    result = (value * 9/5) + 32
    print(f"Temperature in Fahrenheit: {result:.2f} °F")

elif unit == "F":
    result = (value - 32) * 5/9
    print(f"Temperature in Celsius: {result:.2f} °C")

else:
    print("Error: Invalid unit. Please enter C or F.")

Enter temperature value: 25
Enter unit (C or F): c
Temperature in Fahrenheit: 77.00 °F


In [9]:
num = int(input("Enter a 4-digit number: "))

d1 = num // 1000
d2 = (num // 100) % 10
d3 = (num // 10) % 10
d4 = num % 10

sum_digits = d1 + d2 + d3 + d4

print("Sum of digits:", sum_digits)

Enter a 4-digit number: 1234
Sum of digits: 10


In [10]:
value = input("Enter a value: ")

try:
    value = int(value)
    data_type = "int"
except ValueError:
    try:
        value = float(value)
        data_type = "float"
    except ValueError:
        data_type = "str"

print(data_type, value)

Enter a value: 42
int 42


In [13]:
income = float(input("Enter annual income: ₹"))

tax = 0

if income <= 300000:
    tax = 0
    print("Tax on ₹3,00,000: ₹0.00")

elif income <= 700000:
    tax = (income - 300000) * 0.05
    print("Tax on first ₹3,00,000: ₹0.00")
    print(f"Tax on ₹{income - 300000:.2f} at 5%: ₹{tax:.2f}")

elif income <= 1000000:
    tax_5 = 400000 * 0.05
    tax_10 = (income - 700000) * 0.10
    tax = tax_5 + tax_10

    print("Tax on first ₹3,00,000: ₹0.00")
    print("Tax on next ₹4,00,000 at 5%: ₹20,000.00")
    print(f"Tax on remaining ₹{income - 700000:.2f} at 10%: ₹{tax_10:.2f}")

elif income <= 1200000:
    tax_5 = 400000 * 0.05
    tax_10 = 300000 * 0.10
    tax_15 = (income - 1000000) * 0.15
    tax = tax_5 + tax_10 + tax_15

    print("Tax on first ₹3,00,000: ₹0.00")
    print("Tax on ₹3,00,001–₹7,00,000 at 5%: ₹20,000.00")
    print("Tax on ₹7,00,001–₹10,00,000 at 10%: ₹30,000.00")
    print(f"Tax on remaining ₹{income - 1000000:.2f} at 15%: ₹{tax_15:.2f}")

elif income <= 1500000:
    tax_5 = 400000 * 0.05
    tax_10 = 300000 * 0.10
    tax_15 = 200000 * 0.15
    tax_20 = (income - 1200000) * 0.20
    tax = tax_5 + tax_10 + tax_15 + tax_20

    print("Tax on first ₹3,00,000: ₹0.00")
    print("Tax on ₹3,00,001–₹7,00,000 at 5%: ₹20,000.00")
    print("Tax on ₹7,00,001–₹10,00,000 at 10%: ₹30,000.00")
    print("Tax on ₹10,00,001–₹12,00,000 at 15%: ₹30,000.00")
    print(f"Tax on remaining ₹{income - 1200000:.2f} at 20%: ₹{tax_20:.2f}")

else:
    tax_5 = 400000 * 0.05
    tax_10 = 300000 * 0.10
    tax_15 = 200000 * 0.15
    tax_20 = 300000 * 0.20
    tax_30 = (income - 1500000) * 0.30

    tax = tax_5 + tax_10 + tax_15 + tax_20 + tax_30

    print("Tax on first ₹3,00,000: ₹0.00")
    print("Tax on ₹3,00,001–₹7,00,000 at 5%: ₹20,000.00")
    print("Tax on ₹7,00,001–₹10,00,000 at 10%: ₹30,000.00")
    print("Tax on ₹10,00,001–₹12,00,000 at 15%: ₹30,000.00")
    print("Tax on ₹12,00,001–₹15,00,000 at 20%: ₹60,000.00")
    print(f"Tax above ₹15,00,000 at 30%: ₹{tax_30:.2f}")

print("------------------------------")
print(f"Total Income Tax: ₹{tax:.2f}")

Enter annual income: ₹800000
Tax on first ₹3,00,000: ₹0.00
Tax on next ₹4,00,000 at 5%: ₹20,000.00
Tax on remaining ₹100000.00 at 10%: ₹10000.00
------------------------------
Total Income Tax: ₹30000.00


In [14]:
pan = input("Enter PAN: ")

if len(pan) != 10:
    print("Invalid PAN — length must be exactly 10")

elif not pan[:5].isalpha() or not pan[:5].isupper():
    print("Invalid PAN — first 5 characters must be uppercase letters")

elif not pan[5:9].isdigit():
    print("Invalid PAN — characters 6 to 9 must be digits")

elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN — last character must be an uppercase letter")

else:
    print("Valid PAN")

Enter PAN: ABCDE1234F
Valid PAN


In [15]:
units = float(input("Enter units consumed: "))

if units <= 50:
    energy_charge = units * 4.10

elif units <= 100:
    energy_charge = (50 * 4.10) + ((units - 50) * 5.55)

elif units <= 200:
    energy_charge = (50 * 4.10) + (50 * 5.55) + ((units - 100) * 7.10)

else:
    energy_charge = (50 * 4.10) + (50 * 5.55) + (100 * 7.10) + ((units - 200) * 8.15)

fixed_charge = 110
government_tax = (energy_charge + fixed_charge) * 0.06
total_bill = energy_charge + fixed_charge + government_tax

print("\n----- BESCOM Electricity Bill -----")
print(f"Units Consumed: {units:.0f}")
print(f"Energy Charges: ₹{energy_charge:.2f}")
print(f"Fixed Charge: ₹{fixed_charge:.2f}")
print(f"Government Tax (6%): ₹{government_tax:.2f}")
print("-------------------------------")
print(f"Total Bill: ₹{total_bill:.2f}")

Enter units consumed: 150

----- BESCOM Electricity Bill -----
Units Consumed: 150
Energy Charges: ₹837.50
Fixed Charge: ₹110.00
Government Tax (6%): ₹56.85
-------------------------------
Total Bill: ₹1004.35


In [16]:
runs = float(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))

if balls == 0:
    print("Cannot calculate strike rate — balls faced cannot be 0")

else:
    strike_rate = (runs / balls) * 100

    print(f"Strike Rate: {strike_rate:.2f}")

    if strike_rate > 150:
        print("Classification: Explosive (T20 finisher)")

    elif strike_rate > 100:
        print("Classification: Aggressive (Top order T20)")

    elif strike_rate >= 75:
        print("Classification: Steady (ODI anchor)")

    else:
        print("Classification: Defensive (Test match)")

Enter runs scored: 80
Enter balls faced: 40
Strike Rate: 200.00
Classification: Explosive (T20 finisher)


In [17]:
weight = float(input("Enter weight (kg): "))
height_cm = float(input("Enter height (cm): "))

height_m = height_cm / 100

bmi = weight / (height_m ** 2)

print(f"BMI: {bmi:.2f}")

if bmi < 18.5:
    print("Category: Underweight")

elif bmi <= 22.9:
    print("Category: Normal (Indian range)")

elif bmi <= 24.9:
    print("Category: Overweight")

elif bmi <= 29.9:
    print("Category: Obese Class I")

else:
    print("Category: Obese Class II")

Enter weight (kg): 60
Enter height (cm): 165
BMI: 22.04
Category: Normal (Indian range)


In [18]:
N = 5

for i in range(1, N + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [19]:
N = 5

# Upper half
for i in range(1, N + 1):
    print("  " * (N - i), end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

# Lower half
for i in range(N - 1, 0, -1):
    print("  " * (N - i), end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

        1 
      1 2 1 
    1 2 3 2 1 
  1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
  1 2 3 4 3 2 1 
    1 2 3 2 1 
      1 2 1 
        1 


In [1]:
N = 5

for i in range(N):
    for j in range(N):
        if i == 0 or i == N - 1 or j == 0 or j == N - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

* * * * * 
*       * 
*       * 
*       * 
* * * * * 


In [2]:
N = 5

for i in range(N):
    value = 1

    for j in range(i + 1):
        print(value, end=" ")

        value = value * (i - j) // (j + 1)

    print()

1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 


In [3]:
N = 5

for i in range(N):
    for j in range(i + 1):
        print(chr(65 + j), end=" ")
    print()

A 
A B 
A B C 
A B C D 
A B C D E 


In [4]:
armstrong = []

for num in range(1, 10000):
    digits = str(num)
    n = len(digits)

    total = 0
    for digit in digits:
        total += int(digit) ** n

    if total == num:
        armstrong.append(num)

print("Armstrong numbers:", ", ".join(map(str, armstrong)))
print("Count:", len(armstrong))

Armstrong numbers: 1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count: 16


In [5]:
N = int(input("Enter N: "))

a = 0
b = 1
total = 0

for i in range(N):
    print(a, end=" ")
    total += a
    a, b = b, a + b

print()
print("Sum:", total)

Enter N: 5
0 1 1 2 3 
Sum: 7


In [6]:
N = int(input("Enter N: "))

def is_prime(num):
    if num < 2:
        return False

    i = 2
    while i * i <= num:
        if num % i == 0:
            return False
        i += 1

    return True


if is_prime(N):
    print(N, "is Prime")
else:
    print(N, "is Not Prime")

prime_sum = 0

for num in range(2, N + 1):
    if is_prime(num):
        prime_sum += num

print("Sum of primes:", prime_sum)

Enter N: 10
10 is Not Prime
Sum of primes: 17


In [7]:
N = int(input("Enter a number: "))

if N < 0:
    print("Not Palindrome")
else:
    original = N
    reverse = 0

    while N > 0:
        digit = N % 10
        reverse = reverse * 10 + digit
        N = N // 10

    print("Reversed number:", reverse)

    if original == reverse:
        print("Palindrome")
    else:
        print("Not Palindrome")

Enter a number: 121
Reversed number: 121
Palindrome


In [8]:
a = int(input("Enter first positive integer: "))
b = int(input("Enter second positive integer: "))

x = a
y = b

# Euclidean Algorithm
while y != 0:
    x, y = y, x % y

hcf = x

# HCF × LCM = a × b
lcm = (a * b) // hcf

print("HCF:", hcf)
print("LCM:", lcm)

Enter first positive integer: 12
Enter second positive integer: 18
HCF: 6
LCM: 36


In [9]:
sentence = input("Enter a sentence: ")

characters = len(sentence)
words = 0
vowels = 0
consonants = 0
digits = 0
spaces = 0
special = 0

in_word = False

for ch in sentence:
    if ch.isalpha():
        if ch.lower() in "aeiou":
            vowels += 1
        else:
            consonants += 1

        if not in_word:
            words += 1
            in_word = True

    elif ch.isdigit():
        digits += 1
        in_word = False

    elif ch.isspace():
        spaces += 1
        in_word = False

    else:
        special += 1
        in_word = False

print("Total characters:", characters)
print("Total words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special characters:", special)

Enter a sentence: Order came on time,food was hot, packaging 10/10!
Total characters: 49
Total words: 8
Vowels: 14
Consonants: 20
Digits: 4
Spaces: 7
Special characters: 4


In [10]:
marks = list(map(int, input("Enter 10 marks: ").split()))

maximum = marks[0]
minimum = marks[0]

for mark in marks:
    if mark > maximum:
        maximum = mark
    if mark < minimum:
        minimum = mark

average = sum(marks) / len(marks)

above_average = 0
for mark in marks:
    if mark > average:
        above_average += 1

# Find second highest without sort()
highest = maximum
second_highest = None

for mark in marks:
    if mark < highest:
        if second_highest is None or mark > second_highest:
            second_highest = mark

print("Maximum:", maximum)
print("Minimum:", minimum)
print("Average:", average)
print("Students above average:", above_average)
print("Second highest:", second_highest)

Enter 10 marks: 85 72 90 65 78 92 88 70 95 80
Maximum: 95
Minimum: 65
Average: 81.5
Students above average: 5
Second highest: 92


In [11]:
review = input("Enter review: ")

words = review.lower().split()

frequency = {}

for word in words:
    if word in frequency:
        frequency[word] += 1
    else:
        frequency[word] = 1

# Sort by frequency in descending order
sorted_words = sorted(frequency.items(), key=lambda x: x[1], reverse=True)

print("\nWord Frequencies:")
for word, count in sorted_words:
    print(word, ":", count)

most_frequent_word, highest_count = sorted_words[0]

print("\nMost frequent word:", most_frequent_word)
print("Count:", highest_count)

Enter review: Food was hot and food was tasty, food was fresh

Word Frequencies:
food : 3
was : 3
hot : 1
and : 1
tasty, : 1
fresh : 1

Most frequent word: food
Count: 3


In [12]:
states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
    "Kerala": "Thiruvananthapuram",
    "Telangana": "Hyderabad"
}

while True:
    print("\n----- Indian States CRUD -----")
    print("1. Add a new state-capital pair")
    print("2. Update an existing capital")
    print("3. Delete a state")
    print("4. Search a state")
    print("5. Display all states")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        state = input("Enter state: ")
        capital = input("Enter capital: ")
        states[state] = capital
        print("State added successfully.")

    elif choice == "2":
        state = input("Enter state to update: ")

        if state in states:
            capital = input("Enter new capital: ")
            states[state] = capital
            print("Capital updated successfully.")
        else:
            print("State not found.")

    elif choice == "3":
        state = input("Enter state to delete: ")

        if state in states:
            del states[state]
            print("State deleted successfully.")
        else:
            print("State not found.")

    elif choice == "4":
        state = input("Enter state to search: ")

        if state in states:
            print("Capital:", states[state])
        else:
            print("Not found")

    elif choice == "5":
        print("\nStates and Capitals:")
        for state in sorted(states):
            print(state, "->", states[state])

    elif choice == "6":
        print("Program exited.")
        break

    else:
        print("Invalid choice. Please try again.")


----- Indian States CRUD -----
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Enter your choice: 1
Enter state: Capital: Bengaluru
Enter capital: Bengaluru
State added successfully.

----- Indian States CRUD -----
1. Add a new state-capital pair
2. Update an existing capital
3. Delete a state
4. Search a state
5. Display all states
6. Exit
Enter your choice: 6
Program exited.


In [13]:
A = {"Python", "Java", "C++", "SQL"}
B = {"Java", "JavaScript", "Python", "Go", "SQL"}

# (a) Languages known by BOTH sections
both = A & B

# (b) Languages known ONLY by Section A
only_A = A - B

# (c) Languages known ONLY by Section B
only_B = B - A

# (d) Total unique languages
all_languages = A | B

# (e) Languages exclusive to one section
exclusive = A ^ B

print("Both sections:", both)
print("Only Section A:", only_A)
print("Only Section B:", only_B)
print("Total unique languages:", len(all_languages))
print("All unique languages:", all_languages)
print("Exclusive to one section:", exclusive)

Both sections: {'Java', 'Python', 'SQL'}
Only Section A: {'C++'}
Only Section B: {'Go', 'JavaScript'}
Total unique languages: 6
All unique languages: {'Java', 'SQL', 'JavaScript', 'Python', 'C++', 'Go'}
Exclusive to one section: {'JavaScript', 'Go', 'C++'}


In [14]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)

days = ("Monday", "Tuesday", "Wednesday",
        "Thursday", "Friday", "Saturday", "Sunday")

# (a) Maximum price and day
max_price = max(prices)
max_day = days[prices.index(max_price)]

# (b) Minimum price and day
min_price = min(prices)
min_day = days[prices.index(min_price)]

# (c) Average
average = sum(prices) / len(prices)

# (d) Biggest single-day gain
biggest_gain = prices[1] - prices[0]
gain_from = days[0]
gain_to = days[1]

for i in range(1, len(prices)):
    gain = prices[i] - prices[i - 1]

    if gain > biggest_gain:
        biggest_gain = gain
        gain_from = days[i - 1]
        gain_to = days[i]

# (e) Total volatility
volatility = 0

for i in range(1, len(prices)):
    volatility += abs(prices[i] - prices[i - 1])

print("Maximum price:", max_price, "on", max_day)
print("Minimum price:", min_price, "on", min_day)
print("Average price:", round(average, 2))
print("Biggest single-day gain:", biggest_gain,
      "between", gain_from, "and", gain_to)
print("Total volatility:", volatility)

Maximum price: 4055 on Sunday
Minimum price: 3845 on Monday
Average price: 3949.29
Biggest single-day gain: 77 between Wednesday and Thursday
Total volatility: 286


In [15]:
numbers = [
    10, 20, 30, 20, 40, 50, 10, 60, 70, 30,
    80, 90, 100, 50, 110, 120, 130, 140, 150, 160
]

# (a) Set of unique numbers
unique_set = set(numbers)

# Count each number without Counter
frequency = {}

for num in numbers:
    if num in frequency:
        frequency[num] += 1
    else:
        frequency[num] = 1

# (b) Numbers appearing more than once
duplicates = []

# (c) Numbers appearing exactly once
single = []

for num in frequency:
    if frequency[num] > 1:
        duplicates.append(num)
    elif frequency[num] == 1:
        single.append(num)

print("Unique numbers:", unique_set)
print("Numbers appearing more than once:", duplicates)
print("Numbers appearing exactly once:", single)

Unique numbers: {160, 130, 100, 70, 40, 10, 140, 110, 80, 50, 20, 150, 120, 90, 60, 30}
Numbers appearing more than once: [10, 20, 30, 50]
Numbers appearing exactly once: [40, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160]


In [16]:
sentence = input("Enter a sentence: ")

cleaned = ""

for ch in sentence:
    if ch.isalnum():
        cleaned += ch.lower()

if cleaned == cleaned[::-1]:
    print("TRUE")
else:
    print("FALSE")

Enter a sentence: A man, a plan, a canal: Panama
TRUE


In [17]:
sentence = input("Enter a sentence: ")

words = sentence.split()
result = []

for word in words:
    new_word = word[0].upper() + word[1:].lower()
    result.append(new_word)

output = " ".join(result)

print(output)

Enter a sentence: hello world from bengaluru
Hello World From Bengaluru


In [18]:
message = input("Enter message: ")
N = int(input("Enter shift value: "))

encrypted = ""

for ch in message:
    if ch.isupper():
        encrypted += chr((ord(ch) - ord('A') + N) % 26 + ord('A'))

    elif ch.islower():
        encrypted += chr((ord(ch) - ord('a') + N) % 26 + ord('a'))

    else:
        encrypted += ch

print("Encrypted message:", encrypted)

Enter message: Enter message: Hello, India! Enter shift value: 3
Enter shift value: 3
Encrypted message: Hqwhu phvvdjh: Khoor, Lqgld! Hqwhu vkliw ydoxh: 3


In [19]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if gst_inclusive:
        total_amount = amount
        base_amount = amount / (1 + gst_rate / 100)
        gst_amount = total_amount - base_amount
    else:
        base_amount = amount
        gst_amount = amount * gst_rate / 100
        total_amount = base_amount + gst_amount

    return (
        round(base_amount, 2),
        round(gst_amount, 2),
        round(total_amount, 2)
    )


# Test cases
print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


In [20]:
def power(base, exp):
    if exp == 0:
        return 1

    if exp < 0:
        return 1 / power(base, -exp)

    return base * power(base, exp - 1)


# Test cases
print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

1024
1
0.1111111111111111


In [21]:
import numpy as np

# (a) Create a 5x5 identity matrix
matrix = np.eye(5)
print("Original Identity Matrix:")
print(matrix)

# (b) Multiply every element by 10
matrix = matrix * 10
print("\nAfter multiplying by 10:")
print(matrix)

# (c) Transpose the matrix
# The transpose of an identity matrix is itself because
# all non-zero elements are on the main diagonal.
transpose = matrix.T
print("\nTranspose of Matrix:")
print(transpose)

# (d) Sum of diagonal elements
diagonal_sum = np.trace(matrix)
print("\nSum of diagonal elements:", diagonal_sum)

# (e) Sum of all elements
total_sum = np.sum(matrix)
print("Sum of all elements:", total_sum)

Original Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

After multiplying by 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transpose of Matrix:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of diagonal elements: 50.0
Sum of all elements: 50.0


In [22]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

# (a) Total weekly sales
total_sales = np.sum(sales)

# (b) Daily average
average_sales = np.mean(sales)

# (c) Day with maximum sales
max_day = days[np.argmax(sales)]
max_sales = np.max(sales)

# (d) Number of days above weekly average
days_above_average = np.sum(sales > average_sales)

# (e) Percentage growth from Monday to Sunday
growth = ((sales[-1] - sales[0]) / sales[0]) * 100

# (f) Day-on-day percentage changes
daily_changes = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100

print("Total weekly sales: ₹", total_sales)
print("Daily average: ₹", round(average_sales, 2))
print("Maximum sales day:", max_day, "₹", max_sales)
print("Days above average:", days_above_average)
print("Monday to Sunday growth:", round(growth, 2), "%")
print("Day-on-day % changes:", np.round(daily_changes, 2))

Total weekly sales: ₹ 150200
Daily average: ₹ 21457.14
Maximum sales day: Sat ₹ 35200
Days above average: 3
Monday to Sunday growth: 136.67 %
Day-on-day % changes: [ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


In [23]:
import numpy as np

# Create a 5x5 array filled with 1s
matrix = np.ones((5, 5), dtype=int)

# Make the interior elements 0
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
